apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetdm.fullname" . }}
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
    app.kubernetes.io/component: fleetdm
type: Opaque
data:
  mysql-password: {{ .Values.mysql.env.MYSQL_PASSWORD | b64enc | quote }}

