{{- if .Values.mysql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fleetdm.mysql.fullname" . }}
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "fleetdm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "fleetdm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fleetdm.mysql.fullname" . }}
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "fleetdm.mysql.fullname" . }}
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "fleetdm.mysql.fullname" . }}
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fleetdm.mysql.fullname" . }}
              key: mysql-password
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        {{- if .Values.mysql.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "fleetdm.mysql.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}

